server "parallage.symmachus.org" {
    log style combined
    directory { index "index.html" }
    listen on $listen_addr port 80
    root "/vhosts/parallage.symmachus.org/htdocs"

    location "/review/*" {
        authenticate "Parallage Translation Review" with "/vhosts/parallage.symmachus.org/etc/htpasswd"
    }

    location "/cgi-bin/review*.cgi" {
        fastcgi
        root "/vhosts/parallage.symmachus.org"
        authenticate "Parallage Translation Review" with "/vhosts/parallage.symmachus.org/etc/htpasswd"
    }

    location "/db/*" {
        block
    }

    location "/etc/*" {
        block
    }
}
